- name: Condition Check
  hosts: all
  sources:
    - ansible.eda.generic:
        playload:
          - request:
              hostname: eda.lab.example.com
  rules:
    - name: r1
      condition: event.request.hostname == "eda.lab.example.com"
      action:
        print_event:
          pretty: true
